### ISSUE TITLE
Client ID is no longer used

### ISSUE THREAD

**Issue by 618116** [yasuoza/homebridge-open-sesame#181]
It seems Client ID is no longer used for SESAME 3 and 4, so it should not be required.

The URL to get Candyhouse's API Key is changed to https://partners.candyhouse.co/, and it shows only API Key, and not Client ID anymore.

According to Candyhouse, they have deleted Client ID because their Web API does not use Client ID anymore.

**Comment by ample08-strands** [comment]
ClientID from SesameSDK may work.

```
ap-northeast-1:0a1820f1-dbb3-4bca-9227-2a92f6abf0ae
```

**Comment by ample08-strands** [comment]
You can retrieve CLIENT_ID from SesameSDK

**Comment by yasuoza** [comment]
Please try

```json
"homebridge-open-sesame": "0.4.0-beta.0"
```

with leaving `CLIENT_ID` blank at config.json.

Feedbacks are welcome. Thank you!

**Comment by 618116** [comment]
It seems Beta version works for me. Thank you!
