### ISSUE TITLE
Real-time status update without CLIENT_ID

### ISSUE THREAD

**Issue by koppy0927** [yasuoza/homebridge-open-sesame#198]
In 0.4.0-beta.0, real-time status update are supported.
but, CLIENT_ID was already removed.
According to Sesame support, "CLIENT_ID is no longer needed by developing via Sesame SDK."

![mail](https://i.imgur.com/wuM7j6I.png)

Is it possible to update real-time status without CLIENT_ID?

**Comment by yasuoza** [comment]
Please try v0.4.0-beta.2. Thank you!
FYI: https://github.com/mochipon/pysesame3/issues/64

**Comment by koppy0927** [comment]
In v0.4.0-beta.2, status updates from manual lock/unlock and auto-lock are now reflected in real time!!
Thank you for your quick response. :)
