### ISSUE TITLE
Failed to getMechStatus.

### ISSUE THREAD

**Issue by prpatel78** [yasuoza/homebridge-open-sesame#300]
Wondering if you can help me solve an issue. I have a new install of Hoobs and have installed your Sesame plug-in. However, I keep getting the following error in my logs:
"21/03/2022, 15:42:38Open Sesame BridgeOpen SesameERRORFailed to getMechStatus."

Webhooks is enabled on my Candyhouse dashboard:
Webhook Enabled POST  URL: http://XXXXXX:33892

The plug-in is configured as follows:
{
    "platform": "OpenSesame",
    "name": "Open Sesame",
    "port": 33892,
    "apiKey": "XXXXXY",
    "locks": [
        {
            "name": "Backdoor",
            "uuid": "XXXXXXXXX",
            "port": 33892,
            "battery": 100,
            "debug": true
        },
        {
            "name": "Frontdoor",
            "uuid": "XXXXXX",
            "port": 33892,
            "battery": 100,
            "debug": true
        }
    ]
}

**Comment by yasuoza** [comment]
I think your plugin is https://github.com/aschzero/homebridge-sesame. 
Please open issue there. Thank you.
